"""create contacts table

Revision ID: 8b8421244d0d
Revises:
Create Date: 2026-07-16 21:04:18.422910

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8b8421244d0d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("sentiment", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("ai_reply", sa.Text(), nullable=True),
        sa.Column("ai_processed", sa.Boolean(), nullable=False),
        sa.Column("ai_status", sa.String(length=16), nullable=False),
        sa.Column("owner_email_status", sa.String(length=16), nullable=False),
        sa.Column("customer_email_status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_contacts_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_contacts_email"), ["email"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contacts_email"))
        batch_op.drop_index(batch_op.f("ix_contacts_created_at"))

    op.drop_table("contacts")
    # ### end Alembic commands ###
